name: GitHub pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: wasm-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build WASM binary
        run: |
          cargo build --release --no-default-features --target wasm32-unknown-unknown

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: wasm
          path: target/wasm32-unknown-unknown/release/tetris.wasm

  dist:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install wasm-bindgen
        uses: jetli/wasm-bindgen-action@v0.1.0

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: wasm

      - name: Build page
        run: |
          wasm-bindgen --out-dir out --web tetris.wasm
          cp index.html out/
          cp -r assets/ out/

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: out/

  deploy:
    needs: dist
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy GitHub Pages site
        id: deployment
        uses: actions/deploy-pages@v1
