name: WASM

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Install wasm-bindgen
        uses: jetli/wasm-bindgen-action@v0.1.0

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            target/
            ~/.cargo/registry/
          key: build-wasm

      - name: Build WASM binary
        run: |
          cargo build --release --no-default-features --target wasm32-unknown-unknown

      - name: Build page
        run: |
          wasm-bindgen --out-dir out --web target/wasm32-unknown-unknown/release/tetris.wasm
          cp index.html out/
          cp -r assets/ out/

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: out/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy GitHub Pages site
        id: deployment
        uses: actions/deploy-pages@v1
